server:
  port: 8080
spring:
  datasource:
    druid:
      master:
        url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=Asia/Shanghai
        username: root
        password: root
      slave:
        #是否使用此从数据源
        enabled: true
        url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai
        username: root
        password: root
      #初始化线程数量
      initial-size: 5
      #最大连接池数量
      max-active: 20
      #最小空闲数量
      min-idle: 1
      #配置获取连接等待超时的时间
      max-wait: 60000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #连接失败的重试次数
      retryAttemps: 3
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEviction: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictionTime: 300000
      #配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTime: 900000
logging:
  level:
    #配置mapper包路径即可在控制台打印sql
    com.rayson.duodatasource.mapper: debug
